### ISSUE TITLE
Add Coding Questions and Solutions - NO NEED TO GET ASSIGNED

### ISSUE THREAD

**Issue by kaal-coder** [kaal-coder/hacktoberfest2023#150]
Add your self coded codes in the [Coding](https://github.com/kaal-coder/hacktoberfest2023/tree/main/Coding) Folder.
There is no need to get assigned for this issue.
Make sure you give a Star to the Repository. 🌟

You are free to [Follow Me](https://github.com/kaal-coder) !

**Comment by Khushi-74** [comment]
added reverse linked list program #187

**Comment by czarjulius** [comment]
@kaal-coder, I added a listing sequence with Fibonacci [#191 ](https://github.com/kaal-coder/hacktoberfest2023/pull/191)

**Comment by ShreyaShukla03** [comment]
Please check and merge PR#225

**Comment by imdeveshshukla** [comment]
Please assign me this issue

**Comment by czarjulius** [comment]
> Please assign me this issue

The issue already said `NO NEED TO GET ASSIGNED` so you can just start working on it.

**Comment by onkar-kota** [comment]
Hey @kaal-coder please review my PR #244

**Comment by onkar-kota** [comment]
Hey @kaal-coder this PR has not been accepted by Hacktoberfest as it does not follow the value of event. What is the issue can you specify please?

**Comment by Vaishwanavi** [comment]
@kaal-coder  please check and merge #289

**Comment by himadeepthi1** [comment]
@kaal-coder please check and merge #299

**Comment by himadeepthi1** [comment]
@kaal-coder please verify and merge #300

**Comment by Kirti-Pant** [comment]
can I still work on this issue??
