### ISSUE TITLE
Tic Tac Toe in Python

### ISSUE THREAD

**Issue by asryan11** [kaal-coder/hacktoberfest2023#158]
Can you assign me this issue and please add Hacktoberfest label.

**Comment by sammyifelse** [comment]
please assign this to me

**Comment by Gyanendra-Verma** [comment]
I want to contribute, kindly assign this to me @kaal-coder

**Comment by Nandita-rawat** [comment]
I am an avid and fast-paced learner, eager to learn, share my knowledge, and contribute. This opportunity allows me to refine my skills further and provides a platform to showcase my accumulated expertise. Please assign me.
