### ISSUE TITLE
Maximum Subarray Sum using Kadane's Algorithm in Java

### ISSUE THREAD

**Issue by spardha-codinggirl** [kaal-coder/hacktoberfest2023#161]
Hi @kaal-coder , I want to add the solution of the maximum subarray sum by Kadane's Algorithm in Java. Please assign this issue to me.

**Comment by kaal-coder** [comment]
Start working on it @spardha-codinggirl 
All The Best !

**Comment by sammyifelse** [comment]
please assign this to me

**Comment by aayushi-0407** [comment]
Please assign this issue to me @kaal-coder

**Comment by sakshams23** [comment]
Please assign me with this issue I want to contribute.
