### ISSUE TITLE
Music Player-Frontend Project

### ISSUE THREAD

**Issue by rittikadeb** [kaal-coder/hacktoberfest2023#179]
## Description
It is a UI for music player including features like:
  - Spinning images
  - Song details popup
  - Play and pause functionality
  - Switch songs
  - Progress Bar
  - Neon effect

## Stacks Used
* HTML  
* CSS
* JavaScript

**Comment by rittikadeb** [comment]
Please assign me this under Hacktoberfest2023 tag.

**Comment by sakshams23** [comment]
Please assign me with this issue I want to contribute.
