### ISSUE TITLE
Add Notes - NO NEED TO GET ASSIGNED

### ISSUE THREAD

**Issue by kaal-coder** [kaal-coder/hacktoberfest2023#283]
**Add the Notes which you have used or you have made in the [Notes Folder](https://github.com/kaal-coder/hacktoberfest2023/tree/main/Notes).
There is no need to get assigned for this issue.
### Make sure you give a Star to the Repository. 🌟

> You are free to [Follow Me](https://github.com/kaal-coder) !

**Comment by ArceusDev** [comment]
I'm on it

**Comment by lucashchang** [comment]
could i still work on this or is it closed?

**Comment by Kirti-Pant** [comment]
@kaal-coder  I've PR the issue please review it and merge it
