### ISSUE TITLE
Add Frontend Developer Roadmap 

### ISSUE THREAD

**Issue by kaal-coder** [kaal-coder/hacktoberfest2023#302]
Add this in the form of .pdf or .txt in the [RoadMap](https://github.com/kaal-coder/hacktoberfest2023/tree/main/Roadmap) folder.

### Make sure you give a Star to the Repository. 🌟

> You are free to [Follow Me](https://github.com/kaal-coder) !

**Comment by snehpr966** [comment]
please assign it to me.
