### ISSUE TITLE
Add SQL Roadmap 

### ISSUE THREAD

**Issue by kaal-coder** [kaal-coder/hacktoberfest2023#312]
Add this in the form of .pdf or .txt in the [RoadMap](https://github.com/kaal-coder/hacktoberfest2023/tree/main/Roadmap) folder.

### Make sure you give a Star to the Repository. 🌟

> You are free to [Follow Me](https://github.com/kaal-coder) !

**Comment by HarshVR1947** [comment]
Added SQL_Roadmap pdf file. Please check and merge.

**Comment by siya100** [comment]
@kaal-coder 
can you please assign me this issue

**Comment by Nazim9945** [comment]
Please assign this issue under hecktoberfest and merge the PR that I have requested.

**Comment by GitHub-User9999** [comment]
Bhaiya please assign kar lo

**Comment by mayankm1004** [comment]
I have made a really nice roadmap for SQL, please assign me this issue
