### ISSUE TITLE
Add Java Developer Roadmap 

### ISSUE THREAD

**Issue by kaal-coder** [kaal-coder/hacktoberfest2023#313]
Add this in the form of .pdf or .txt in the [RoadMap](https://github.com/kaal-coder/hacktoberfest2023/tree/main/Roadmap) folder.

### Make sure you give a Star to the Repository. 🌟

> You are free to [Follow Me](https://github.com/kaal-coder) !

**Comment by FarazRashid** [comment]
Added a roadmap, I was a little unsure whether you were checking issues so I thought I would contribute to it directly
